#!/usr/bin/env bash
# Epiloop Docker Installation Script for Mac
# Usage: ./install-mac.sh

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."

    # Check Docker
    if ! command -v docker &> /dev/null; then
        log_error "Docker not found. Please install Docker Desktop for Mac:"
        echo "  brew install --cask docker"
        echo "  OR download from: https://www.docker.com/products/docker-desktop/"
        exit 1
    fi

    # Check Docker is running
    if ! docker info &> /dev/null; then
        log_error "Docker is not running. Please start Docker Desktop."
        exit 1
    fi

    # Check Docker Compose
    if ! docker compose version &> /dev/null; then
        log_error "Docker Compose not available. Please update Docker Desktop."
        exit 1
    fi

    log_success "All prerequisites met"
}

# Create directories
setup_directories() {
    log_info "Creating directories..."
    mkdir -p "$HOME/.epiloop"
    mkdir -p "$HOME/clawd"
    log_success "Directories created"
}

# Prompt for API key
get_api_key() {
    log_info "API Key Configuration"
    echo ""
    echo "You need at least one LLM provider API key."
    echo "Recommended: Anthropic Claude (https://console.anthropic.com/)"
    echo ""

    if [[ -f "$HOME/.epiloop/.env" ]] && grep -q "ANTHROPIC_API_KEY=sk-" "$HOME/.epiloop/.env"; then
        log_info "Found existing API key in ~/.epiloop/.env"
        read -p "Use existing key? [Y/n]: " use_existing
        if [[ "${use_existing:-Y}" =~ ^[Yy]$ ]]; then
            return 0
        fi
    fi

    read -p "Enter your Anthropic API key (sk-ant-...): " api_key

    if [[ -z "$api_key" ]]; then
        log_warn "No API key provided. You'll need to add it later to ~/.epiloop/.env"
        api_key=""
    fi

    # Create .env file
    cat > "$HOME/.epiloop/.env" << EOF
# Epiloop Configuration
# Generated by install-mac.sh on $(date)

# LLM Providers
ANTHROPIC_API_KEY=${api_key}
# OPENAI_API_KEY=
# GOOGLE_API_KEY=
# OPENROUTER_API_KEY=

# Gateway settings
EPILOOP_CONFIG_DIR=$HOME/.epiloop
EPILOOP_WORKSPACE_DIR=$HOME/clawd
EPILOOP_GATEWAY_TOKEN=
EOF

    log_success "Configuration saved to ~/.epiloop/.env"
}

# Build and start
build_and_start() {
    log_info "Building Docker image (this may take a few minutes)..."

    # Source env file for docker-setup.sh
    export EPILOOP_CONFIG_DIR="$HOME/.epiloop"
    export EPILOOP_WORKSPACE_DIR="$HOME/clawd"

    if [[ -f "$HOME/.epiloop/.env" ]]; then
        set -a
        source "$HOME/.epiloop/.env"
        set +a
    fi

    # Run the official setup script
    ./docker-setup.sh
}

# Print next steps
print_next_steps() {
    echo ""
    echo "=============================================="
    echo -e "${GREEN}Epiloop is now running in Docker!${NC}"
    echo "=============================================="
    echo ""
    echo "Next steps:"
    echo ""
    echo "1. Open the dashboard:"
    echo "   docker compose run --rm epiloop-cli dashboard --no-open"
    echo ""
    echo "2. Set up WhatsApp:"
    echo "   docker compose run --rm epiloop-cli channels login"
    echo "   (Scan QR code with WhatsApp → Linked Devices)"
    echo ""
    echo "3. Set up Google Chat:"
    echo "   See: INSTALL_DOCKER_MAC.md (Step 7)"
    echo ""
    echo "4. View logs:"
    echo "   docker compose logs -f epiloop-gateway"
    echo ""
    echo "5. Check channel status:"
    echo "   docker compose run --rm epiloop-cli channels status"
    echo ""
    echo "Documentation: https://docs.clawd.bot/"
    echo ""
}

# Main
main() {
    echo "=============================================="
    echo "  Epiloop Docker Installation for Mac"
    echo "=============================================="
    echo ""

    check_prerequisites
    setup_directories
    get_api_key
    build_and_start
    print_next_steps
}

main "$@"
