export const browserCoreExamples = [
  "epiloop browser status",
  "epiloop browser start",
  "epiloop browser stop",
  "epiloop browser tabs",
  "epiloop browser open https://example.com",
  "epiloop browser focus abcd1234",
  "epiloop browser close abcd1234",
  "epiloop browser screenshot",
  "epiloop browser screenshot --full-page",
  "epiloop browser screenshot --ref 12",
  "epiloop browser snapshot",
  "epiloop browser snapshot --format aria --limit 200",
  "epiloop browser snapshot --efficient",
  "epiloop browser snapshot --labels",
];

export const browserActionExamples = [
  "epiloop browser navigate https://example.com",
  "epiloop browser resize 1280 720",
  "epiloop browser click 12 --double",
  'epiloop browser type 23 "hello" --submit',
  "epiloop browser press Enter",
  "epiloop browser hover 44",
  "epiloop browser drag 10 11",
  "epiloop browser select 9 OptionA OptionB",
  "epiloop browser upload /tmp/file.pdf",
  'epiloop browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "epiloop browser dialog --accept",
  'epiloop browser wait --text "Done"',
  "epiloop browser evaluate --fn '(el) => el.textContent' --ref 7",
  "epiloop browser console --level error",
  "epiloop browser pdf",
];
