#!/bin/bash
#
# improvement-manager.sh - CLI Interface for Improvement PRD Review and Management
#
# This module provides shell functions and a CLI interface for reviewing and managing
# improvement PRDs generated by the self-improvement pipeline. It wraps the Python
# improvement-prd-generator.py module for shell integration with claude-loop.sh.
#
# Features:
# - List improvements with status filtering
# - Review improvement PRD details
# - Approve/reject PRDs with notes
# - Execute approved PRDs with claude-loop
# - Track improvement history
#
# Usage:
#   source lib/improvement-manager.sh
#   list_improvements
#   review_improvement <prd_name>
#   approve_improvement <prd_name> [notes]
#   reject_improvement <prd_name> <reason>
#   execute_improvement <prd_name>
#
# CLI:
#   ./lib/improvement-manager.sh list [--status STATUS]
#   ./lib/improvement-manager.sh review <prd_name>
#   ./lib/improvement-manager.sh approve <prd_name> [--notes "..."]
#   ./lib/improvement-manager.sh reject <prd_name> --reason "..."
#   ./lib/improvement-manager.sh execute <prd_name>
#   ./lib/improvement-manager.sh history
#   ./lib/improvement-manager.sh pending
#

set -euo pipefail

# ============================================================================
# Configuration
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${SCRIPT_DIR}/.."
IMPROVEMENTS_DIR="${PROJECT_ROOT}/.claude-loop/improvements"
HISTORY_FILE="${PROJECT_ROOT}/.claude-loop/improvement_history.jsonl"
PRD_GENERATOR="${SCRIPT_DIR}/improvement-prd-generator.py"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# ============================================================================
# Helper Functions
# ============================================================================

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_improvement() {
    echo -e "${MAGENTA}[IMPROVEMENT]${NC} $1"
}

check_python() {
    if ! command -v python3 &> /dev/null; then
        log_error "Python 3 is required but not found"
        return 1
    fi
}

check_prd_generator() {
    if [ ! -f "$PRD_GENERATOR" ]; then
        log_error "PRD generator not found: $PRD_GENERATOR"
        return 1
    fi
}

ensure_improvements_dir() {
    if [ ! -d "$IMPROVEMENTS_DIR" ]; then
        mkdir -p "$IMPROVEMENTS_DIR"
    fi
}

ensure_history_file() {
    local history_dir
    history_dir=$(dirname "$HISTORY_FILE")
    if [ ! -d "$history_dir" ]; then
        mkdir -p "$history_dir"
    fi
    if [ ! -f "$HISTORY_FILE" ]; then
        touch "$HISTORY_FILE"
    fi
}

get_timestamp() {
    date -u +%Y-%m-%dT%H:%M:%SZ
}

# ============================================================================
# Core Functions
# ============================================================================

#
# List all improvement PRDs
#
# Arguments:
#   $1 - status filter (optional): pending_review, approved, rejected, in_progress, complete, all
#   $2 - output format (optional): text, json
#
# Returns:
#   0 on success, 1 on error
#
list_improvements() {
    local status="${1:-all}"
    local format="${2:-text}"

    check_python || return 1
    check_prd_generator || return 1

    if [ "$format" = "json" ]; then
        python3 "$PRD_GENERATOR" list --status "$status" --json
    else
        python3 "$PRD_GENERATOR" list --status "$status"
    fi
}

#
# Get count of pending review PRDs
#
# Returns:
#   Number of pending PRDs
#
get_pending_count() {
    check_python || return 1
    check_prd_generator || return 1

    local count
    count=$(python3 "$PRD_GENERATOR" pending --json 2>/dev/null | jq 'length' 2>/dev/null) || count=0
    echo "$count"
}

#
# Review (show details of) an improvement PRD
#
# Arguments:
#   $1 - PRD name
#   $2 - output format (optional): text, json
#
# Returns:
#   0 on success, 1 if PRD not found
#
review_improvement() {
    local prd_name="$1"
    local format="${2:-text}"

    if [ -z "$prd_name" ]; then
        log_error "PRD name is required"
        return 1
    fi

    check_python || return 1
    check_prd_generator || return 1

    if [ "$format" = "json" ]; then
        python3 "$PRD_GENERATOR" show "$prd_name" --json
    else
        python3 "$PRD_GENERATOR" show "$prd_name"
    fi
}

#
# Approve an improvement PRD for implementation
#
# Arguments:
#   $1 - PRD name
#   $2 - reviewer notes (optional)
#
# Returns:
#   0 on success, 1 on error
#
approve_improvement() {
    local prd_name="$1"
    local notes="${2:-}"

    if [ -z "$prd_name" ]; then
        log_error "PRD name is required"
        return 1
    fi

    check_python || return 1
    check_prd_generator || return 1

    local result
    if [ -n "$notes" ]; then
        result=$(python3 "$PRD_GENERATOR" approve "$prd_name" --notes "$notes" 2>&1) || {
            log_error "Failed to approve PRD: $prd_name"
            echo "$result"
            return 1
        }
    else
        result=$(python3 "$PRD_GENERATOR" approve "$prd_name" 2>&1) || {
            log_error "Failed to approve PRD: $prd_name"
            echo "$result"
            return 1
        }
    fi

    log_success "PRD '$prd_name' approved"

    # Log to history
    log_history_entry "$prd_name" "approved" "$notes"

    return 0
}

#
# Reject an improvement PRD
#
# Arguments:
#   $1 - PRD name
#   $2 - rejection reason (required)
#
# Returns:
#   0 on success, 1 on error
#
reject_improvement() {
    local prd_name="$1"
    local reason="${2:-}"

    if [ -z "$prd_name" ]; then
        log_error "PRD name is required"
        return 1
    fi

    if [ -z "$reason" ]; then
        log_error "Rejection reason is required"
        return 1
    fi

    check_python || return 1
    check_prd_generator || return 1

    local result
    result=$(python3 "$PRD_GENERATOR" reject "$prd_name" --reason "$reason" 2>&1) || {
        log_error "Failed to reject PRD: $prd_name"
        echo "$result"
        return 1
    }

    log_success "PRD '$prd_name' rejected"

    # Log to history
    log_history_entry "$prd_name" "rejected" "$reason"

    return 0
}

#
# Start (mark as in_progress) an improvement PRD
#
# Arguments:
#   $1 - PRD name
#
# Returns:
#   0 on success, 1 on error
#
start_improvement() {
    local prd_name="$1"

    if [ -z "$prd_name" ]; then
        log_error "PRD name is required"
        return 1
    fi

    check_python || return 1
    check_prd_generator || return 1

    local result
    result=$(python3 "$PRD_GENERATOR" start "$prd_name" 2>&1) || {
        log_error "Failed to start PRD: $prd_name"
        echo "$result"
        return 1
    }

    log_success "PRD '$prd_name' marked as in progress"

    # Log to history
    log_history_entry "$prd_name" "started" ""

    return 0
}

#
# Complete (mark as complete) an improvement PRD
#
# Arguments:
#   $1 - PRD name
#
# Returns:
#   0 on success, 1 on error
#
complete_improvement() {
    local prd_name="$1"

    if [ -z "$prd_name" ]; then
        log_error "PRD name is required"
        return 1
    fi

    check_python || return 1
    check_prd_generator || return 1

    local result
    result=$(python3 "$PRD_GENERATOR" complete "$prd_name" 2>&1) || {
        log_error "Failed to complete PRD: $prd_name"
        echo "$result"
        return 1
    }

    log_success "PRD '$prd_name' marked as complete"

    # Log to history
    log_history_entry "$prd_name" "completed" ""

    return 0
}

#
# Rollback an improvement PRD by reverting its commits
#
# Arguments:
#   $1 - PRD name
#   $2 - reason for rollback (optional)
#   $3 - dry_run flag (optional): "true" to show what would happen
#
# Returns:
#   0 on success, 1 on error
#
rollback_improvement() {
    local prd_name="$1"
    local reason="${2:-}"
    local dry_run="${3:-false}"

    if [ -z "$prd_name" ]; then
        log_error "PRD name is required"
        return 1
    fi

    check_python || return 1

    local rollback_script="${SCRIPT_DIR}/improvement-rollback.py"
    if [ ! -f "$rollback_script" ]; then
        log_error "Rollback script not found: $rollback_script"
        return 1
    fi

    log_warn "Rolling back improvement PRD: $prd_name"

    local flags=""
    if [ -n "$reason" ]; then
        flags="--reason \"$reason\""
    fi
    if [ "$dry_run" = "true" ]; then
        flags="$flags --dry-run"
        log_info "DRY RUN - no changes will be made"
    fi

    local exit_code=0
    if [ -n "$reason" ]; then
        if [ "$dry_run" = "true" ]; then
            python3 "$rollback_script" rollback "$prd_name" --reason "$reason" --dry-run || exit_code=$?
        else
            python3 "$rollback_script" rollback "$prd_name" --reason "$reason" || exit_code=$?
        fi
    else
        if [ "$dry_run" = "true" ]; then
            python3 "$rollback_script" rollback "$prd_name" --dry-run || exit_code=$?
        else
            python3 "$rollback_script" rollback "$prd_name" || exit_code=$?
        fi
    fi

    if [ $exit_code -eq 0 ]; then
        if [ "$dry_run" != "true" ]; then
            log_success "PRD '$prd_name' rolled back successfully"
            log_history_entry "$prd_name" "rolled_back" "$reason"
        fi
    else
        log_error "Rollback failed for PRD: $prd_name"
    fi

    return $exit_code
}

#
# Validate an improvement PRD before execution
#
# Arguments:
#   $1 - PRD name
#   $2 - force flag (optional): "true" to force validation despite blocking conditions
#
# Returns:
#   0 if validation passes, 1 if blocked
#
validate_improvement() {
    local prd_name="$1"
    local force="${2:-false}"

    if [ -z "$prd_name" ]; then
        log_error "PRD name is required"
        return 1
    fi

    check_python || return 1

    local prd_path="${IMPROVEMENTS_DIR}/${prd_name}.json"
    if [ ! -f "$prd_path" ]; then
        log_error "PRD not found: $prd_name"
        return 1
    fi

    local validator="${SCRIPT_DIR}/improvement-validator.py"
    if [ ! -f "$validator" ]; then
        log_error "Improvement validator not found: $validator"
        return 1
    fi

    log_info "Validating improvement PRD: $prd_name"

    local force_flag=""
    if [ "$force" = "true" ]; then
        force_flag="--force"
        log_warn "Force mode enabled - will bypass blocking conditions"
    fi

    local exit_code=0
    python3 "$validator" validate "$prd_path" $force_flag || exit_code=$?

    if [ $exit_code -eq 0 ]; then
        log_success "Validation passed"
        log_history_entry "$prd_name" "validated" "passed"
    else
        log_error "Validation failed - deployment blocked"
        log_history_entry "$prd_name" "validated" "failed"
    fi

    return $exit_code
}

#
# Execute an approved improvement PRD with claude-loop
#
# Arguments:
#   $1 - PRD name
#   $2 - validate flag (optional): "true" to run validation before execution
#   $3 - force flag (optional): "true" to force validation despite blocking conditions
#
# Returns:
#   0 on success, 1 on error
#
execute_improvement() {
    local prd_name="$1"
    local validate="${2:-false}"
    local force="${3:-false}"

    if [ -z "$prd_name" ]; then
        log_error "PRD name is required"
        return 1
    fi

    check_python || return 1
    check_prd_generator || return 1

    # Check if PRD exists and is approved
    local prd_path="${IMPROVEMENTS_DIR}/${prd_name}.json"
    if [ ! -f "$prd_path" ]; then
        log_error "PRD not found: $prd_name"
        return 1
    fi

    local status
    status=$(jq -r '.status // ""' "$prd_path")

    if [ "$status" != "approved" ]; then
        log_error "PRD '$prd_name' is not approved (current status: $status)"
        log_info "Use --approve-improvement to approve it first"
        return 1
    fi

    # Run validation if requested
    if [ "$validate" = "true" ]; then
        log_info "Running pre-deployment validation..."
        if ! validate_improvement "$prd_name" "$force"; then
            if [ "$force" != "true" ]; then
                log_error "Deployment blocked by validation failure"
                log_info "Use --force to override (with warning)"
                return 1
            fi
        fi
    fi

    log_improvement "Executing improvement PRD: $prd_name"

    # Mark as in_progress
    start_improvement "$prd_name" || return 1

    # Copy the improvement PRD to the main prd.json location
    local branch_name
    branch_name=$(jq -r '.branchName // "feature/improvement"' "$prd_path")

    log_info "Branch: $branch_name"
    log_info "Copying PRD to prd.json..."

    # Backup current prd.json if exists
    if [ -f "${PROJECT_ROOT}/prd.json" ]; then
        local backup_name="prd-backup-$(date +%Y%m%d_%H%M%S).json"
        cp "${PROJECT_ROOT}/prd.json" "${PROJECT_ROOT}/${backup_name}"
        log_info "Backed up existing prd.json to $backup_name"
    fi

    # Copy improvement PRD to main location
    cp "$prd_path" "${PROJECT_ROOT}/prd.json"

    # Log execution start
    log_history_entry "$prd_name" "execution_started" ""

    # Execute with claude-loop
    log_info "Starting claude-loop..."

    local exit_code=0
    "${PROJECT_ROOT}/claude-loop.sh" || exit_code=$?

    if [ $exit_code -eq 0 ]; then
        log_success "Improvement PRD executed successfully"
        complete_improvement "$prd_name"
        log_history_entry "$prd_name" "execution_completed" "success"
    else
        log_warn "Improvement PRD execution ended with code $exit_code"
        log_history_entry "$prd_name" "execution_completed" "exit_code=$exit_code"
    fi

    return $exit_code
}

#
# Log an entry to the improvement history file
#
# Arguments:
#   $1 - PRD name
#   $2 - action (approved, rejected, started, completed, execution_started, execution_completed)
#   $3 - details/notes
#
log_history_entry() {
    local prd_name="$1"
    local action="$2"
    local details="${3:-}"
    local timestamp
    timestamp=$(get_timestamp)

    ensure_history_file

    # Create JSON entry (compact format for JSONL)
    local entry
    entry=$(jq -cn \
        --arg prd "$prd_name" \
        --arg action "$action" \
        --arg details "$details" \
        --arg timestamp "$timestamp" \
        '{prd_name: $prd, action: $action, details: $details, timestamp: $timestamp}')

    echo "$entry" >> "$HISTORY_FILE"
}

#
# Show improvement history
#
# Arguments:
#   $1 - number of entries to show (optional, default: 20)
#   $2 - output format (optional): text, json
#
show_history() {
    local count="${1:-20}"
    local format="${2:-text}"

    ensure_history_file

    if [ ! -s "$HISTORY_FILE" ]; then
        log_info "No improvement history found"
        return 0
    fi

    if [ "$format" = "json" ]; then
        tail -n "$count" "$HISTORY_FILE" | jq -s '.'
    else
        echo ""
        echo "=== Improvement History (last $count entries) ==="
        echo ""
        printf "%-40s %-20s %-25s %s\n" "PRD Name" "Action" "Timestamp" "Details"
        echo "--------------------------------------------------------------------------------------------------------"

        tail -n "$count" "$HISTORY_FILE" | while read -r line; do
            local prd_name action timestamp details
            prd_name=$(echo "$line" | jq -r '.prd_name // ""')
            action=$(echo "$line" | jq -r '.action // ""')
            timestamp=$(echo "$line" | jq -r '.timestamp // ""' | cut -c1-19)
            details=$(echo "$line" | jq -r '.details // ""' | cut -c1-30)

            printf "%-40s %-20s %-25s %s\n" "$prd_name" "$action" "$timestamp" "$details"
        done
    fi
}

#
# Get summary statistics for improvements
#
# Arguments:
#   $1 - output format (optional): text, json
#
get_summary() {
    local format="${1:-text}"

    check_python || return 1
    check_prd_generator || return 1

    if [ "$format" = "json" ]; then
        python3 "$PRD_GENERATOR" summary --json
    else
        python3 "$PRD_GENERATOR" summary
    fi
}

#
# Show pending PRDs for review
#
# Arguments:
#   $1 - output format (optional): text, json
#
show_pending() {
    local format="${1:-text}"

    check_python || return 1
    check_prd_generator || return 1

    if [ "$format" = "json" ]; then
        python3 "$PRD_GENERATOR" pending --json
    else
        python3 "$PRD_GENERATOR" pending
    fi
}

# ============================================================================
# CLI Interface
# ============================================================================

show_cli_help() {
    cat << EOF
improvement-manager.sh - CLI Interface for Improvement PRD Review and Management

USAGE:
    ./lib/improvement-manager.sh <command> [options]

COMMANDS:
    list [--status STATUS]           List all improvement PRDs
                                     STATUS: pending_review, approved, rejected, in_progress, complete, all

    review <prd_name>                Show details of a specific PRD

    approve <prd_name> [--notes "..."]
                                     Approve a PRD for implementation

    reject <prd_name> --reason "..." Reject a PRD with a reason

    validate <prd_name> [--force]    Validate a PRD before deployment
                                     --force: bypass blocking conditions

    execute <prd_name> [--validate] [--force]
                                     Execute an approved PRD with claude-loop
                                     --validate: run validation before execution
                                     --force: bypass validation blocking conditions

    start <prd_name>                 Mark a PRD as in_progress

    complete <prd_name>              Mark a PRD as complete

    rollback <prd_name> [--reason "..."] [--dry-run]
                                     Rollback an improvement by reverting commits
                                     --reason: specify reason for rollback
                                     --dry-run: show what would happen without changes

    pending                          List PRDs pending review

    history [--count N]              Show improvement history (default: last 20)

    summary                          Show summary statistics

OPTIONS:
    --json                           Output in JSON format
    --validate                       Run validation before execution
    --force                          Bypass blocking conditions (with warning)
    --dry-run                        Show what would happen without changes (for rollback)
    -h, --help                       Show this help message

EXAMPLES:
    # List all pending PRDs
    ./lib/improvement-manager.sh list --status pending_review

    # Review a specific PRD
    ./lib/improvement-manager.sh review improve-file-handling-abc123

    # Approve with notes
    ./lib/improvement-manager.sh approve improve-file-handling-abc123 --notes "Looks good, proceed"

    # Reject with reason
    ./lib/improvement-manager.sh reject improve-ui-interaction-xyz789 --reason "Too risky, needs more testing"

    # Validate before execution
    ./lib/improvement-manager.sh validate improve-file-handling-abc123

    # Execute with validation
    ./lib/improvement-manager.sh execute improve-file-handling-abc123 --validate

    # Force execution despite validation failures
    ./lib/improvement-manager.sh execute improve-file-handling-abc123 --validate --force

    # Rollback an improvement
    ./lib/improvement-manager.sh rollback improve-file-handling-abc123 --reason "Caused test failures"

    # Dry run rollback to see what would happen
    ./lib/improvement-manager.sh rollback improve-file-handling-abc123 --dry-run

EOF
}

# Main CLI handler
main() {
    if [ $# -eq 0 ]; then
        show_cli_help
        exit 1
    fi

    local command="$1"
    shift

    case "$command" in
        list)
            local status="all"
            local format="text"
            while [[ $# -gt 0 ]]; do
                case $1 in
                    --status)
                        status="$2"
                        shift 2
                        ;;
                    --json)
                        format="json"
                        shift
                        ;;
                    *)
                        log_error "Unknown option: $1"
                        exit 1
                        ;;
                esac
            done
            list_improvements "$status" "$format"
            ;;

        review)
            if [ $# -lt 1 ]; then
                log_error "PRD name is required"
                exit 1
            fi
            local prd_name="$1"
            shift
            local format="text"
            while [[ $# -gt 0 ]]; do
                case $1 in
                    --json)
                        format="json"
                        shift
                        ;;
                    *)
                        log_error "Unknown option: $1"
                        exit 1
                        ;;
                esac
            done
            review_improvement "$prd_name" "$format"
            ;;

        approve)
            if [ $# -lt 1 ]; then
                log_error "PRD name is required"
                exit 1
            fi
            local prd_name="$1"
            shift
            local notes=""
            while [[ $# -gt 0 ]]; do
                case $1 in
                    --notes)
                        notes="$2"
                        shift 2
                        ;;
                    *)
                        log_error "Unknown option: $1"
                        exit 1
                        ;;
                esac
            done
            approve_improvement "$prd_name" "$notes"
            ;;

        reject)
            if [ $# -lt 1 ]; then
                log_error "PRD name is required"
                exit 1
            fi
            local prd_name="$1"
            shift
            local reason=""
            while [[ $# -gt 0 ]]; do
                case $1 in
                    --reason)
                        reason="$2"
                        shift 2
                        ;;
                    *)
                        log_error "Unknown option: $1"
                        exit 1
                        ;;
                esac
            done
            if [ -z "$reason" ]; then
                log_error "Rejection reason is required (use --reason \"...\")"
                exit 1
            fi
            reject_improvement "$prd_name" "$reason"
            ;;

        validate)
            if [ $# -lt 1 ]; then
                log_error "PRD name is required"
                exit 1
            fi
            local prd_name="$1"
            shift
            local force="false"
            while [[ $# -gt 0 ]]; do
                case $1 in
                    --force)
                        force="true"
                        shift
                        ;;
                    *)
                        log_error "Unknown option: $1"
                        exit 1
                        ;;
                esac
            done
            validate_improvement "$prd_name" "$force"
            ;;

        execute)
            if [ $# -lt 1 ]; then
                log_error "PRD name is required"
                exit 1
            fi
            local prd_name="$1"
            shift
            local validate="false"
            local force="false"
            while [[ $# -gt 0 ]]; do
                case $1 in
                    --validate)
                        validate="true"
                        shift
                        ;;
                    --force)
                        force="true"
                        shift
                        ;;
                    *)
                        log_error "Unknown option: $1"
                        exit 1
                        ;;
                esac
            done
            execute_improvement "$prd_name" "$validate" "$force"
            ;;

        start)
            if [ $# -lt 1 ]; then
                log_error "PRD name is required"
                exit 1
            fi
            start_improvement "$1"
            ;;

        complete)
            if [ $# -lt 1 ]; then
                log_error "PRD name is required"
                exit 1
            fi
            complete_improvement "$1"
            ;;

        rollback)
            if [ $# -lt 1 ]; then
                log_error "PRD name is required"
                exit 1
            fi
            local prd_name="$1"
            shift
            local reason=""
            local dry_run="false"
            while [[ $# -gt 0 ]]; do
                case $1 in
                    --reason)
                        reason="$2"
                        shift 2
                        ;;
                    --dry-run)
                        dry_run="true"
                        shift
                        ;;
                    *)
                        log_error "Unknown option: $1"
                        exit 1
                        ;;
                esac
            done
            rollback_improvement "$prd_name" "$reason" "$dry_run"
            ;;

        pending)
            local format="text"
            while [[ $# -gt 0 ]]; do
                case $1 in
                    --json)
                        format="json"
                        shift
                        ;;
                    *)
                        log_error "Unknown option: $1"
                        exit 1
                        ;;
                esac
            done
            show_pending "$format"
            ;;

        history)
            local count=20
            local format="text"
            while [[ $# -gt 0 ]]; do
                case $1 in
                    --count)
                        count="$2"
                        shift 2
                        ;;
                    --json)
                        format="json"
                        shift
                        ;;
                    *)
                        log_error "Unknown option: $1"
                        exit 1
                        ;;
                esac
            done
            show_history "$count" "$format"
            ;;

        summary)
            local format="text"
            while [[ $# -gt 0 ]]; do
                case $1 in
                    --json)
                        format="json"
                        shift
                        ;;
                    *)
                        log_error "Unknown option: $1"
                        exit 1
                        ;;
                esac
            done
            get_summary "$format"
            ;;

        -h|--help|help)
            show_cli_help
            exit 0
            ;;

        *)
            log_error "Unknown command: $command"
            show_cli_help
            exit 1
            ;;
    esac
}

# Run main if script is executed directly (not sourced)
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
